"""initial schema

Revision ID: 6c29a416f050
Revises: 
Create Date: 2026-03-19 12:35:51.606934
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c29a416f050'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_context',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('responses_received', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'COMPLETED', name='conversationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_context_user_id'), ['user_id'], unique=False)

    op.create_table('correction_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('field_corrected', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('rule_extracted', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_log_user_id'), ['user_id'], unique=False)

    op.create_table('invocation_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('model_alias', sa.String(length=100), nullable=False),
    sa.Column('model_actual', sa.String(length=200), nullable=False),
    sa.Column('input_hash', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('eval_session_id', sa.String(length=36), nullable=True),
    sa.Column('spot_check_queued', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invocation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invocation_log_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invocation_log_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_invocation_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_invocation_log_user_id'), ['user_id'], unique=False)

    op.create_table('learned_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action', sa.JSON(), nullable=True),
    sa.Column('supporting_corrections', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learned_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learned_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.Enum('PERSONAL', 'WORK', 'FAMILY', name='taskdomain'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BACKLOG', 'SCHEDULED', 'IN_PROGRESS', 'BLOCKED', 'WAITING_INPUT', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline_type', sa.Enum('HARD', 'SOFT', 'NONE', name='deadlinetype'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=200), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('parent_task', sa.String(length=36), nullable=True),
    sa.Column('prep_work_flag', sa.Boolean(), nullable=False),
    sa.Column('prep_work_instructions', sa.Text(), nullable=True),
    sa.Column('agent_eligible', sa.Boolean(), nullable=False),
    sa.Column('assigned_agent', sa.String(length=100), nullable=True),
    sa.Column('agent_status', sa.Enum('PENDING', 'GATHERING_REQUIREMENTS', 'IN_PROGRESS', 'REVIEW', 'COMPLETE', 'FAILED', name='agentstatus'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_via', sa.Enum('SMS', 'DISCORD', 'SLACK', 'APP', 'EMAIL', 'VOICE', name='inputchannel'), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=200), nullable=True),
    sa.Column('donna_managed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    with op.batch_alter_table('learned_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learned_preferences_user_id'))

    op.drop_table('learned_preferences')
    with op.batch_alter_table('invocation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invocation_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_invocation_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_invocation_log_task_type'))
        batch_op.drop_index(batch_op.f('ix_invocation_log_task_id'))

    op.drop_table('invocation_log')
    with op.batch_alter_table('correction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_log_user_id'))

    op.drop_table('correction_log')
    with op.batch_alter_table('conversation_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_context_user_id'))

    op.drop_table('conversation_context')
    # ### end Alembic commands ###
